### ISSUE TITLE
Code panics

### ISSUE THREAD

**Issue by Kumariz0** [Frostie314159/fake-airplay#1]
The code panics at `fake-airplay-0.1.1/src/lib.rs:60:23`
   `let ev_loop = service.register().unwrap();`

My code:
```rust
use fake_airplay::{create_service, DeviceType};

fn main() {
    let name = "Ass".to_string();
    let device_type = DeviceType::AppleTV;

    let handle = create_service(name, device_type);

    // Wait for the service thread to finish
    handle.join().unwrap();
}

```

**Comment by Frostie314159** [comment]
This is caused by the avahi daemon not running. I added an error message for this in #c626c2d88b701cd202302f2f995f6a58e5540759
